#!/usr/bin/env python3
"""Generate a mechanical ledger from the manuscript directory."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
MANUSCRIPT = ROOT / "manuscript"
OUTPUT = ROOT / "planning" / "manuscript-ledger.md"


def word_count(text):
    return len(re.findall(r"\S+", text))


def state(text, storyboards):
    if not text.strip():
        return "Empty"
    if storyboards:
        return f"Incomplete; {len(storyboards)} storyboard marker(s)"
    return "Drafted"


def main():
    rows = []
    markers = []
    for path in sorted(MANUSCRIPT.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        storyboard_lines = [
            number
            for number, line in enumerate(lines, 1)
            if line.startswith("[STORYBOARD")
        ]
        rows.append(
            (
                int(path.name[:2]) + 1,
                path.name,
                len(lines),
                word_count(text),
                state(text, storyboard_lines),
            )
        )
        markers.extend((path.name, number, lines[number - 1]) for number in storyboard_lines)

    output = [
        "# Manuscript ledger",
        "",
        "Generated by `make ledger`. Do not edit this file by hand.",
        "",
        "This ledger records mechanical state only. It does not summarize the story.",
        "",
        "| Slot | File | Lines | Words | State |",
        "|---:|---|---:|---:|---|",
    ]
    output.extend(
        f"| {slot} | `{name}` | {lines} | {words} | {status} |"
        for slot, name, lines, words, status in rows
    )
    output.extend(("", "## Storyboards", ""))
    if markers:
        output.extend(f"- `{name}:{number}`: `{line}`" for name, number, line in markers)
    else:
        output.append("None.")
    output.append("")
    OUTPUT.write_text("\n".join(output), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
